"""
Cognitive Core - Downstream Artifact Types

These are output types produced by external systems, RPA bots, API calls,
or human operators acting on the specifications generated by the primitive layer.

They are NOT primitive output schemas — no primitive produces these directly.
They are the artifact types that downstream consumers return when reporting
the results of executing an action specification.

The primitive layer produces action specifications (via Generate).
The Govern primitive determines conditions for execution.
These artifact types record what actually happened downstream.
"""

from typing import Any, Optional

try:
    from pydantic import BaseModel, Field
except ImportError:
    class Field:  # type: ignore[no-redef]
        def __init__(self, **kwargs): pass
        def __call__(self, **kwargs): return self

    class BaseModel:  # type: ignore[no-redef]
        def __init__(self, **kwargs):
            for k, v in kwargs.items():
                setattr(self, k, v)
        def model_dump(self):
            return {k: v for k, v in self.__dict__.items() if not k.startswith('_')}


# ---------------------------------------------------------------------------
# Execution artifact types
# ---------------------------------------------------------------------------

class ActionExecution(BaseModel):
    """Record of a single action executed by a downstream system."""
    action: str = Field(description="The action that was attempted")
    target_system: str = Field(description="The system or service the action targeted")
    status: str = Field(description="executed | simulated | blocked | failed")
    confirmation_id: Optional[str] = Field(
        default=None,
        description="Confirmation or transaction ID from the target system"
    )
    response_data: Optional[dict] = Field(
        default=None,
        description="Response payload from the target system"
    )
    error: Optional[str] = Field(
        default=None,
        description="Error message if the action failed"
    )
    latency_ms: Optional[float] = Field(
        default=None,
        description="Execution latency in milliseconds"
    )
    reversible: bool = Field(
        default=True,
        description="Whether this action can be rolled back"
    )
    rollback_handle: Optional[str] = Field(
        default=None,
        description="Identifier to reverse this action if needed"
    )


class AuthorizationCheck(BaseModel):
    """Record of an authorization check performed before action execution."""
    check: str = Field(
        description="What was checked (e.g. 'supervisor_approval', 'amount_threshold')"
    )
    result: str = Field(description="passed | failed | waived | not_applicable")
    reason: str = Field(default="", description="Why this check passed or failed")


class ExecutionArtifact(BaseModel):
    """
    Artifact returned by a downstream system after executing an action specification.

    This is what an RPA bot, API integration, or human operator returns to the
    coordinator after acting on a Generate output or WorkOrder. It is NOT a
    primitive output — it is the downstream confirmation of execution.

    Previously named ActOutput when act was a primitive. Retained here for
    backward compatibility with any downstream systems that produce this shape.
    """
    mode: str = Field(description="execution | dry_run | approval_required")
    actions_taken: list[ActionExecution] = Field(
        default_factory=list,
        description="Actions that were executed, simulated, or blocked"
    )
    authorization_checks: list[AuthorizationCheck] = Field(
        default_factory=list,
        description="Authorization checks performed before execution"
    )
    side_effects: list[str] = Field(
        default_factory=list,
        description="Known side effects of the actions taken"
    )
    requires_human_approval: bool = Field(
        default=False,
        description="Whether any action requires human approval before proceeding"
    )
    approval_brief: Optional[str] = Field(
        default=None,
        description="Summary for the human approver if approval is required"
    )


# Backward-compatibility alias — external systems that previously used ActOutput
# by name can import it from here.
ActOutput = ExecutionArtifact
